class_name GameConfig
extends RefCounted

## All V0.1 balance and schedule values live here. Tests may pass an adjusted copy.
static func make() -> Dictionary:
	return {
		"simulation": {
			"fixed_step": 0.1,
			"spatial_cell_size": 96.0,
			"seed": 240817,
			"max_steps_per_frame": 24,
		},
		"rabbit": {
			"move_speed": 38.0,
			"flee_speed": 72.0,
			"steering": 4.8,
			"hunger_rate": 1.45,
			"hungry_at": 27.0,
			"food_detection_radius": 175.0,
			"fox_detection_radius": 105.0,
			"flee_release_radius": 132.0,
			"eat_distance": 13.0,
			"eat_rate": 4.5,
			"food_value": 7.5,
			"mating_radius": 82.0,
			"reproduction_cooldown": 22.0,
			"reproduction_hunger_max": 34.0,
			"reproduction_food_needed": 10.0,
			"local_food_needed": 5.0,
			"adult_age": 8.0,
			"starvation_threshold": 78.0,
			"starvation_duration": 16.0,
			"lifespan": 225.0,
			"recent_food_decay": 0.34,
			"birth_litter_min": 1,
			"birth_litter_max": 2,
			"newborn_cooldown": 18.0,
			"max_population": 400,
		},
		"fox": {
			"move_speed": 44.0,
			"chase_speed": 64.0,
			"steering": 3.8,
			"hunger_rate": 1.05,
			"hunt_at": 25.0,
			"prey_detection_radius": 235.0,
			"capture_distance": 12.0,
			"capture_rate": 1.7,
			"meal_value": 58.0,
			"mating_radius": 105.0,
			"reproduction_cooldown": 72.0,
			"reproduction_hunger_max": 28.0,
			"reproduction_food_needed": 34.0,
			"adult_age": 18.0,
			"starvation_threshold": 82.0,
			"starvation_duration": 24.0,
			"lifespan": 330.0,
			"recent_food_decay": 0.28,
			"newborn_cooldown": 55.0,
			"max_population": 80,
		},
		"plants": {
			"grass": {
				"max_food": 17.0,
				"regeneration": 0.58,
				"attraction": 1.0,
			},
			"berry_bush": {
				"max_food": 30.0,
				"regeneration": 0.42,
				"attraction": 1.75,
			},
		},
		"world": {
			"initial_radius": 360.0,
			"expansion_interval": 75.0,
			"expansion_amount": 145.0,
			"maximum_radius": 940.0,
			"forest_patch_count": 27,
			"forest_patch_min_radius": 95.0,
			"forest_patch_max_radius": 205.0,
			"placement_clearance": 9.0,
		},
		"inventory": {
			"rabbit": 7,
			"fox": 2,
			"grass": 7,
			"berry_bush": 5,
		},
		"supply": {
			"interval": 60.0,
			"bundles": [
				{"name": "Meadow starters", "items": {"rabbit": 2, "grass": 3}},
				{"name": "Berry refuge", "items": {"rabbit": 2, "berry_bush": 2}},
				{"name": "Forest balance", "items": {"fox": 1, "grass": 3}},
				{"name": "Fresh growth", "items": {"grass": 4, "berry_bush": 1}},
				{"name": "Wild pair", "items": {"rabbit": 3, "fox": 1}},
				{"name": "Forage patch", "items": {"grass": 2, "berry_bush": 2}},
			],
		},
		"objectives": [
			{"name": "Establish", "targets": {"rabbit": 8}, "duration": 15.0},
			{"name": "Balance", "targets": {"rabbit": 12, "fox": 2}, "duration": 20.0},
			{"name": "Thrive", "targets": {"rabbit": 15, "fox": 3}, "duration": 30.0},
		],
	}
