class_name GameConfig
extends RefCounted

const WORLD_EXPANSION_STEP := 48.0

## V0.5 compound progression plus the V0.4 terrain and balance values live here.
static func make() -> Dictionary:
	return {
		"simulation": {
			"fixed_step": 0.1,
			"spatial_cell_size": 96.0,
			"seed": 240817,
			"max_steps_per_frame": 24,
		},
		"rabbit": {
			"move_speed": 38.0,
			"flee_speed": 72.0,
			"steering": 4.8,
			"speed_variation": 0.18,
			"turn_variation": 0.35,
			"hunger_threshold_variation": 4.0,
			"caution_variation": 0.14,
			"decision_interval_min": 0.18,
			"decision_interval_max": 0.55,
			"wander_turn_rate": 0.9,
			"wander_turn_response": 2.8,
			"wander_noise_interval_min": 0.45,
			"wander_noise_interval_max": 1.25,
			"personal_space_min": 20.0,
			"personal_space_max": 30.0,
			"separation_strength": 0.58,
			"food_crowding_penalty": 26.0,
			# One complete fixed-step bite. Smaller scraps do not count as a usable
			# meal even before a patch crosses its depletion threshold.
			"minimum_food_bite": 0.45,
			"hunger_rate": 1.45,
			# Rabbits begin looking before they are in visible distress. Hunger still
			# controls appetite, but food should be a noticeable influence on movement.
			"hungry_at": 20.0,
			# Once feeding starts, rabbits finish a meal before roaming again. This
			# lower release threshold prevents one-bite trips back to the same plant.
			"sated_at": 11.0,
			# UI warning starts well before starvation, leaving roughly 30 seconds
			# to react at 1x even when a rabbit cannot find food.
			"hunger_warning_at": 56.0,
			# This remains for local nursery/progression evidence. Rabbit food
			# acquisition uses it as each Rabbit's local vision limit.
			"food_detection_radius": 175.0,
			# Nearby Rabbits share their current local vision through a connected
			# social group. Keep this smaller than food vision so social awareness is
			# earned by staying together rather than being global by default.
			"social_proximity_radius": 50.0,
			"fox_detection_radius": 105.0,
			"flee_release_radius": 132.0,
			"eat_distance": 13.0,
			"eat_rate": 4.5,
			"food_value": 7.5,
			"mating_radius": 82.0,
			"reproduction_cooldown": 22.0,
			"reproduction_hunger_max": 34.0,
			"reproduction_food_needed": 10.0,
			"local_food_needed": 14.0,
			"adult_age": 8.0,
			"starvation_threshold": 78.0,
			"starvation_duration": 16.0,
			"lifespan": 225.0,
			"recent_food_decay": 0.34,
			"birth_litter_min": 1,
			"birth_litter_max": 2,
			"newborn_cooldown": 18.0,
			"max_population": 400,
		},
		"fox": {
			"move_speed": 44.0,
			"chase_speed": 64.0,
			"steering": 3.8,
			"hunger_rate": 0.85,
			"hunt_at": 18.0,
			"prey_detection_radius": 260.0,
			"capture_distance": 12.0,
			"capture_rate": 2.0,
			"meal_value": 62.0,
			"mating_radius": 105.0,
			"reproduction_cooldown": 72.0,
			"reproduction_hunger_max": 28.0,
			"reproduction_food_needed": 34.0,
			"adult_age": 18.0,
			"starvation_threshold": 82.0,
			"starvation_duration": 30.0,
			"lifespan": 330.0,
			"recent_food_decay": 0.28,
			"newborn_cooldown": 55.0,
			"max_population": 80,
		},
		"plants": {
			"carrot_patch": {
				"max_food": 14.0,
				"regeneration": 0.42,
				"abundant_ratio": 0.70,
				"healthy_ratio": 0.35,
				"depleted_ratio": 0.10,
				# Fast Carrots need a higher release threshold to remain visibly out of
				# service for about 15 seconds rather than returning as tiny bites.
				"recovery_ratio": 0.52,
			},
			"berry_bush": {
				"max_food": 24.0,
				"regeneration": 0.34,
				"abundant_ratio": 0.70,
				"healthy_ratio": 0.35,
				"depleted_ratio": 0.10,
				"recovery_ratio": 0.42,
			},
		},
		"world": {
			"initial_radius": 360.0,
			"expansion_amount": WORLD_EXPANSION_STEP,
			"maximum_radius": 940.0,
			"forest_patch_count": 27,
			"forest_patch_min_radius": 95.0,
			"forest_patch_max_radius": 205.0,
			"placement_clearance": 9.0,
		},
		"terrain": {
			"query_bin_size": 240.0,
			"woodland": {
				"fox_patrol_search_radius": 420.0,
				"fox_patrol_cover_target": 0.58,
				"fox_patrol_replan_interval": 4.5,
				"fox_wander_steering_strength": 0.62,
			},
			"thicket": {
				"patch_count": 22,
				"patch_min_radius": 44.0,
				"patch_max_radius": 88.0,
				"rabbit_speed_factor": 0.99,
				"fox_speed_factor": 0.58,
				"fox_capture_rate_factor": 0.38,
				"fox_capture_range_factor": 0.72,
				"refuge_search_radius": 230.0,
				"refuge_cover_min": 0.48,
				"refuge_threat_detection_factor": 1.38,
				"refuge_evasion_speed_factor": 0.82,
			},
			"stream": {
				"enabled": true,
				"point_count": 49,
				"initial_offset_ratio": 0.34,
				"meander": 78.0,
				"half_width_min": 25.0,
				"half_width_max": 35.0,
				"deep_water_threshold": 0.34,
				"ford_positions": [0.19, 0.48, 0.81],
				"ford_radius": 38.0,
			},
			"routing": {
				"path_sample_spacing": 11.0,
				"bank_approach_clearance": 34.0,
				"waypoint_reached_distance": 17.0,
				"moving_target_replan_distance": 34.0,
				"moving_target_replan_interval": 0.55,
			},
			"food_suitability": {
				"carrot_minimum": 0.42,
				"carrot_meadow_bonus": 0.78,
				"carrot_maximum": 1.20,
				"berry_base": 0.62,
				"berry_margin_peak": 0.46,
				"berry_margin_bonus": 0.62,
				"berry_deep_cover_start": 0.68,
				"berry_deep_cover_penalty": 0.34,
				"berry_minimum": 0.46,
				"berry_maximum": 1.24,
				"poor_capacity_factor": 0.48,
				"rich_capacity_factor": 1.28,
			},
		},
		"inventory": {
			"rabbit": 7,
			"fox": 0,
			"carrot_patch": 7,
			"berry_bush": 5,
		},
		"supply": {
			"interval": 90.0,
			"pools": {
				"meadow": [
					{"name": "Carrot starters", "items": {"rabbit": 1, "carrot_patch": 1}},
					{"name": "Berry refuge", "items": {"rabbit": 1, "berry_bush": 1}},
					{"name": "Fresh harvest", "items": {"carrot_patch": 2, "berry_bush": 1}},
					{"name": "Forage patch", "items": {"carrot_patch": 1, "berry_bush": 1}},
				],
				"web": [
					{"name": "Carrot renewal", "items": {"rabbit": 1, "carrot_patch": 1}},
					{"name": "Berry refuge", "items": {"rabbit": 1, "berry_bush": 1}},
					{"name": "Forest balance", "items": {"fox": 1, "carrot_patch": 1}},
					{"name": "Fresh harvest", "items": {"carrot_patch": 2, "berry_bush": 1}},
					{"name": "Wild pair", "items": {"rabbit": 1, "fox": 1}},
					{"name": "Forage patch", "items": {"carrot_patch": 1, "berry_bush": 1}},
				],
				"living": [
					{"name": "Carrot renewal", "items": {"carrot_patch": 2}},
					{"name": "Berry refuge", "items": {"berry_bush": 2}},
					{"name": "Forest balance", "items": {"fox": 1, "carrot_patch": 1}},
					{"name": "Wild balance", "items": {"rabbit": 1, "fox": 1}},
					{"name": "Fresh harvest", "items": {"carrot_patch": 2, "berry_bush": 1}},
					{"name": "Dense forage", "items": {"carrot_patch": 1, "berry_bush": 2}},
				],
			},
			"first_collapse_bundle": {"name": "Carrot starters", "items": {"rabbit": 2, "carrot_patch": 1}},
		},
		"progression": {
			"initial_unlocked": ["rabbit", "carrot_patch", "berry_bush"],
			"initial_supply_pool": "meadow",
			"trend_sample_interval": 1.0,
			"trend_history_duration": 35.0,
			"spatial_sample_interval": 0.5,
			# Retain this evaluator key for compatibility. Player-facing copy calls
			# every qualifying rabbit group a nursery.
			"safe_havens": {
				"minimum_groups": 2,
				"rabbits_per_group": 2,
				"minimum_separation": 300.0,
				"minimum_local_food": 14.0,
			},
			"milestones": [
				{
					"id": "colony_gathers",
					"tier": "minor",
					"title": "A Colony Gathers",
					"summary": "Bring 4 rabbits into the meadow.",
					"display_populations": ["rabbit"],
					"rabbit_min": 4,
					"fox_min": 0,
					"criteria": [],
					"stabilization": 4.0,
					"labels": {
						"low": "The first rabbits are gathering...",
						"stabilizing": "The colony is settling...",
					},
					"guidance": "Place four rabbits near a patch of food so the colony starts with room to grow.",
					"teaser": "Next, the colony will need to grow on its own.",
					"completion_message": "A rabbit colony has gathered",
					"effects": {"expand_world": WORLD_EXPANSION_STEP},
				},
				{
					"id": "new_arrivals",
					"tier": "minor",
					"title": "New Arrivals",
					"summary": "Reach 6 rabbits, including 2 born in the meadow.",
					"display_populations": ["rabbit"],
					"rabbit_min": 6,
					"fox_min": 0,
					"criteria": [
						{
							"id": "new_rabbits",
							"type": "rabbit_birth",
							"label": "Rabbits born here",
							"metric_label": "NATURAL BIRTHS",
							"target": 2,
						},
					],
					"stabilization": 6.0,
					"labels": {
						"low": "The colony still needs room to grow...",
						"evidence": "Waiting for new rabbits...",
						"stabilizing": "The new arrivals are settling...",
					},
					"guidance": "Keep adult rabbits together near good food and give them time to start families.",
					"teaser": "The young will soon need to find food for themselves.",
					"completion_message": "Two new rabbits were born",
					"effects": {"expand_world": WORLD_EXPANSION_STEP},
				},
				{
					"id": "young_foragers",
					"tier": "minor",
					"title": "Young Foragers",
					"summary": "Reach 8 rabbits and help 2 meadow-born rabbits grow and eat.",
					"display_populations": ["rabbit"],
					"rabbit_min": 8,
					"fox_min": 0,
					"criteria": [
						{
							"id": "young_rabbits_fed",
							"type": "born_rabbit_fed",
							"label": "Young rabbits grow and feed",
							"metric_label": "YOUNG FORAGERS",
							"target": 2,
							"minimum_age": 8.0,
							"fresh_only": false,
						},
					],
					"stabilization": 8.0,
					"labels": {
						"low": "The growing colony needs more rabbits...",
						"evidence": "The young are learning to forage...",
						"stabilizing": "The young foragers are thriving...",
					},
					"guidance": "Keep the meadow-born rabbits near replenishing food while they grow.",
					"teaser": "Next, new life must take hold across the meadow.",
					"completion_message": "The young rabbits can forage",
					"effects": {"expand_world": WORLD_EXPANSION_STEP},
				},
				{
					"id": "birthplaces",
					"tier": "minor",
					"title": "Life Across the Meadow",
					"summary": "Reach 10 rabbits and have births in 3 separate areas.",
					"display_populations": ["rabbit"],
					"rabbit_min": 10,
					"fox_min": 0,
					"criteria": [
						{
							"id": "three_birthplaces",
							"type": "separated_birth_zones",
							"label": "Separated birthplaces",
							"metric_label": "BIRTHPLACES",
							"target": 3,
							# Birth areas are local breeding neighborhoods, not large map regions.
							# Keep this close to the scale of a rabbit's food reach so two
							# nearby families can still register as distinct.
							"minimum_separation": 140.0,
						},
					],
					"stabilization": 8.0,
					"labels": {
						"low": "The colony needs more rabbits...",
						"evidence": "Waiting for families in different places...",
						"stabilizing": "New life is spreading...",
					},
					"guidance": "Build three well-spaced food patches and keep a breeding pair near each one.",
					"teaser": "Those new families now need lasting homes.",
					"completion_message": "New life has spread across the meadow",
					"effects": {"expand_world": WORLD_EXPANSION_STEP},
				},
				{
					"id": "nursery_network",
					"tier": "major",
					"title": "A Nursery Network",
					"summary": "Reach 12 rabbits and sustain 3 separate nurseries.",
					"display_populations": ["rabbit"],
					"rabbit_min": 12,
					"fox_min": 0,
					"criteria": [
						{
							"id": "nurseries",
							"type": "safe_havens",
							"label": "Stable nursery groups",
							"metric_label": "NURSERIES",
							"lens_label": "Nursery",
							# Three sites make the rabbit opening's strategic capstone. By this
							# point four smaller checkpoint expansions have opened enough room,
							# and the Objective Lens identifies each recognized live nursery.
							"target": 3,
							"rabbits_per_group": 3,
							"minimum_separation": 280.0,
							# Nursery evidence needs reachable usable forage nearby, not a hidden
							# biomass quota. Later nursery checkpoints keep their stronger reserve.
							"minimum_local_food": 0.0,
						},
					],
					"stabilization": 10.0,
					"labels": {
						"low": "The nursery network needs a stronger colony...",
						"evidence": "Building three lasting nurseries...",
						"stabilizing": "The nursery network is holding...",
					},
					"guidance": "A nursery has at least three rabbits gathered around usable nearby food. Sustain three well-spaced nurseries at the same time.",
					"teaser": "Tracks have appeared. Something else is watching the meadow.",
					"completion_message": "Three nurseries are thriving · Foxes have arrived",
					"effects": {
						"expand_world": WORLD_EXPANSION_STEP,
						"unlock": ["fox"],
						"introduction": {"fox": 2},
						"supply_pool": "web",
						"arm_rabbit_failure": true,
					},
				},
				{
					"id": "first_hunt",
					"tier": "minor",
					"title": "Hunt and Recover",
					"summary": "Let a fox kill 1 rabbit, then have 1 rabbit born.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 6,
					"fox_min": 1,
					"criteria": [
						{
							"id": "recovery_cycle",
							"type": "ordered_cycle",
							"label": "Hunt then renewal",
							"metric_label": "RECOVERY RHYTHM",
						},
					],
					"event_sequence": ["hunt", "birth"],
					"evidence_window": 120.0,
					"stabilization": 7.0,
					"decline_window": 14.0,
					"severe_decline_fraction": 0.40,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The food web is not ready...",
						"evidence": "Waiting for hunt and recovery...",
						"starving": "The prey population needs food...",
						"declining": "Predation is overwhelming the colony...",
						"stabilizing": "The colony has recovered...",
					},
					"guidance": "Keep the rabbits fed after the hunt and give the meadow time to renew.",
					"teaser": "The meadow is learning how to live with a hunter.",
					"completion_message": "The colony recovered after the hunt",
					"effects": {"expand_world": WORLD_EXPANSION_STEP},
				},
				{
					"id": "life_returns",
					"tier": "major",
					"title": "Predator–Prey Rhythm",
					"summary": "Complete a fox kill → rabbit birth → fox kill.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 7,
					"fox_min": 1,
					"criteria": [
						{
							"id": "predator_prey_cycle",
							"type": "ordered_cycle",
							"label": "Hunt, renewal, hunt",
							"metric_label": "FOOD-WEB RHYTHM",
						},
					],
					"event_sequence": ["hunt", "birth", "hunt"],
					"evidence_window": 150.0,
					"stabilization": 10.0,
					"decline_window": 16.0,
					"severe_decline_fraction": 0.38,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The food web is still too fragile...",
						"evidence": "Building a predator–prey rhythm...",
						"starving": "One side of the food web needs support...",
						"declining": "Hunting is outpacing renewal...",
						"stabilizing": "The rhythm is holding...",
					},
					"guidance": "Give the rabbits enough food and space for hunts and new life to take turns.",
					"teaser": "The meadow will soon face pressure in more than one place.",
					"completion_message": "The predator–prey rhythm holds · the meadow opens",
					"effects": {
						"expand_world": WORLD_EXPANSION_STEP,
						"introduction": {"fox": 1},
					},
				},
				{
					"id": "two_safe_havens",
					"tier": "minor",
					"title": "Nurseries Under Pressure",
					"summary": "Keep 2 separate nurseries fed through a fox kill, then a rabbit birth.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 8,
					"fox_min": 1,
					"criteria": [
						{
							"id": "safe_havens",
							"type": "safe_havens",
							"label": "Separated nurseries",
							"metric_label": "NURSERIES",
							"lens_label": "Nursery",
							"target": 2,
						},
						{
							"id": "pressure_recovery",
							"type": "ordered_cycle",
							"label": "Hunt followed by renewal",
							"metric_label": "PRESSURE RHYTHM",
						},
					],
					"event_sequence": ["hunt", "birth"],
					"evidence_window": 150.0,
					"stabilization": 12.0,
					"decline_window": 18.0,
					"severe_decline_fraction": 0.38,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The nursery network is still fragile...",
						"evidence": "Testing the nurseries under pressure...",
						"starving": "One nursery needs reachable food...",
						"declining": "The colony is losing ground...",
						"stabilizing": "Both nurseries survived the cycle...",
					},
					"guidance": "Keep two nurseries fed and let the foxes move through without emptying either one.",
					"teaser": "Two hunters are waiting to find their places.",
					"completion_message": "The nurseries survived pressure",
					"effects": {"expand_world": WORLD_EXPANSION_STEP},
				},
				{
					"id": "predators_find_place",
					"tier": "major",
					"title": "Two Hunting Foxes",
					"summary": "Keep 2 foxes alive; each must kill a rabbit.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 10,
					"fox_min": 2,
					"criteria": [
						{
							"id": "safe_havens",
							"type": "safe_havens",
							"label": "Separated nurseries",
							"metric_label": "NURSERIES",
							"lens_label": "Nursery",
							"target": 3,
						},
						{
							"id": "shared_cycle",
							"type": "ordered_cycle",
							"label": "Hunt, renewal, hunt",
							"metric_label": "SHARED RHYTHM",
						},
						{
							"id": "distinct_predators",
							"type": "distinct_foxes_fed",
							"label": "Different foxes hunt",
							"metric_label": "FOXES FED",
							"target": 2,
						},
						{
							"id": "prey_reserve",
							"type": "prey_per_fox",
							"label": "Four rabbits per fox",
							"metric_label": "PREY PER FOX",
							"target": 4,
						},
					],
					"event_sequence": ["hunt", "birth", "hunt"],
					"evidence_window": 180.0,
					"stabilization": 14.0,
					"decline_window": 20.0,
					"severe_decline_fraction": 0.36,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The food web cannot support both predators yet...",
						"evidence": "The predators are sharing the web...",
						"starving": "The food web is under pressure...",
						"declining": "Predation is overwhelming the colony...",
						"stabilizing": "The shared web is balancing...",
					},
					"guidance": "Spread out food and rabbits so both foxes can feed while life continues.",
					"teaser": "The whole meadow is about to find its own rhythm.",
					"completion_message": "Predators have found their place · the meadow opens",
					"effects": {
						"expand_world": WORLD_EXPANSION_STEP,
						"introduction": {"fox": 1},
						"supply_pool": "living",
					},
				},
				{
					"id": "living_ecosystem",
					"tier": "final",
					"title": "Living Ecosystem",
					"summary": "Complete kill → birth → kill → birth → kill with both foxes.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 12,
					"fox_min": 2,
					"criteria": [
						{
							"id": "safe_havens",
							"type": "safe_havens",
							"label": "Separated nurseries",
							"metric_label": "NURSERIES",
							"lens_label": "Nursery",
							"target": 3,
						},
						{
							"id": "living_cycle",
							"type": "ordered_cycle",
							"label": "Hunt, birth, hunt, birth, hunt",
							"metric_label": "LIVING RHYTHM",
						},
						{
							"id": "distinct_predators",
							"type": "distinct_foxes_fed",
							"label": "Different foxes hunt",
							"metric_label": "FOXES FED",
							"target": 2,
						},
						{
							"id": "distributed_renewal",
							"type": "separated_birth_zones",
							"label": "Renewal across nurseries",
							"metric_label": "BIRTHPLACES",
							"target": 2,
							"minimum_separation": 140.0,
						},
						{
							"id": "prey_reserve",
							"type": "prey_per_fox",
							"label": "Four rabbits per fox",
							"metric_label": "PREY PER FOX",
							"target": 4,
						},
					],
					"event_sequence": ["hunt", "birth", "hunt", "birth", "hunt"],
					"evidence_window": 210.0,
					"stabilization": 20.0,
					"decline_window": 24.0,
					"severe_decline_fraction": 0.34,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The food web is under strain...",
						"evidence": "Life is finding its rhythm...",
						"starving": "The food web needs support...",
						"declining": "The web is beginning to unravel...",
						"stabilizing": "Holding together...",
					},
					"guidance": "Keep food in several places and let hunts and new life take turns.",
					"teaser": "What happens next belongs to the meadow.",
					"completion_message": "Ecosystem Established",
					"effects": {"complete_run": true},
				},
			],
			"critical": {
				"breeding_group": 2,
				"entry_debounce": 4.0,
				"recovery_population": 2,
				"recovery_settling": 8.0,
				"grace_duration": 45.0,
				"first_rescue_delay": 6.0,
				"recent_event_window": 90.0,
			},
		},
	}
