class_name GameConfig
extends RefCounted

## V0.4 terrain plus the preserved V0.3 balance/progression values live here.
static func make() -> Dictionary:
	return {
		"simulation": {
			"fixed_step": 0.1,
			"spatial_cell_size": 96.0,
			"seed": 240817,
			"max_steps_per_frame": 24,
		},
		"rabbit": {
			"move_speed": 38.0,
			"flee_speed": 72.0,
			"steering": 4.8,
			"speed_variation": 0.18,
			"turn_variation": 0.35,
			"hunger_threshold_variation": 4.0,
			"caution_variation": 0.14,
			"decision_interval_min": 0.18,
			"decision_interval_max": 0.55,
			"wander_turn_rate": 0.9,
			"wander_turn_response": 2.8,
			"wander_noise_interval_min": 0.45,
			"wander_noise_interval_max": 1.25,
			"personal_space_min": 20.0,
			"personal_space_max": 30.0,
			"separation_strength": 0.58,
			"food_crowding_penalty": 26.0,
			"food_choice_variation": 9.0,
			"target_commitment_bonus": 16.0,
			"hunger_rate": 1.45,
			"hungry_at": 27.0,
			# Once feeding starts, rabbits finish a meal before roaming again. This
			# lower release threshold prevents one-bite trips back to the same plant.
			"sated_at": 11.0,
			# UI warning starts well before starvation, leaving roughly 30 seconds
			# to react at 1x even when a rabbit cannot find food.
			"hunger_warning_at": 56.0,
			"food_detection_radius": 175.0,
			"fox_detection_radius": 105.0,
			"flee_release_radius": 132.0,
			"eat_distance": 13.0,
			"eat_rate": 4.5,
			"food_value": 7.5,
			"mating_radius": 82.0,
			"reproduction_cooldown": 22.0,
			"reproduction_hunger_max": 34.0,
			"reproduction_food_needed": 10.0,
			"local_food_needed": 14.0,
			"adult_age": 8.0,
			"starvation_threshold": 78.0,
			"starvation_duration": 16.0,
			"lifespan": 225.0,
			"recent_food_decay": 0.34,
			"birth_litter_min": 1,
			"birth_litter_max": 2,
			"newborn_cooldown": 18.0,
			"max_population": 400,
		},
		"fox": {
			"move_speed": 44.0,
			"chase_speed": 64.0,
			"steering": 3.8,
			"hunger_rate": 0.85,
			"hunt_at": 18.0,
			"prey_detection_radius": 260.0,
			"capture_distance": 12.0,
			"capture_rate": 2.0,
			"meal_value": 62.0,
			"mating_radius": 105.0,
			"reproduction_cooldown": 72.0,
			"reproduction_hunger_max": 28.0,
			"reproduction_food_needed": 34.0,
			"adult_age": 18.0,
			"starvation_threshold": 82.0,
			"starvation_duration": 30.0,
			"lifespan": 330.0,
			"recent_food_decay": 0.28,
			"newborn_cooldown": 55.0,
			"max_population": 80,
		},
		"plants": {
			"carrot_patch": {
				"max_food": 14.0,
				"regeneration": 0.42,
				"attraction": 1.0,
			},
			"berry_bush": {
				"max_food": 24.0,
				"regeneration": 0.34,
				"attraction": 1.75,
			},
		},
		"world": {
			"initial_radius": 360.0,
			"expansion_amount": 145.0,
			"maximum_radius": 940.0,
			"forest_patch_count": 27,
			"forest_patch_min_radius": 95.0,
			"forest_patch_max_radius": 205.0,
			"placement_clearance": 9.0,
		},
		"terrain": {
			"query_bin_size": 240.0,
			"thicket": {
				"patch_count": 22,
				"patch_min_radius": 44.0,
				"patch_max_radius": 88.0,
				"rabbit_speed_factor": 0.96,
				"fox_speed_factor": 0.74,
				"fox_capture_rate_factor": 0.58,
				"fox_capture_range_factor": 0.84,
				"refuge_search_radius": 190.0,
				"refuge_cover_min": 0.48,
			},
			"stream": {
				"enabled": true,
				"point_count": 49,
				"initial_offset_ratio": 0.47,
				"meander": 62.0,
				"half_width_min": 20.0,
				"half_width_max": 28.0,
				"deep_water_threshold": 0.34,
				"ford_positions": [0.22, 0.47, 0.76],
				"ford_radius": 40.0,
			},
			"routing": {
				"path_sample_spacing": 11.0,
				"waypoint_reached_distance": 17.0,
				"moving_target_replan_distance": 34.0,
				"moving_target_replan_interval": 0.55,
			},
			"food_suitability": {
				"carrot_minimum": 0.42,
				"carrot_meadow_bonus": 0.78,
				"carrot_maximum": 1.20,
				"berry_base": 0.62,
				"berry_margin_peak": 0.46,
				"berry_margin_bonus": 0.62,
				"berry_deep_cover_start": 0.68,
				"berry_deep_cover_penalty": 0.34,
				"berry_minimum": 0.46,
				"berry_maximum": 1.24,
			},
		},
		"inventory": {
			"rabbit": 7,
			"fox": 0,
			"carrot_patch": 7,
			"berry_bush": 5,
		},
		"supply": {
			"interval": 90.0,
			"pools": {
				"meadow": [
					{"name": "Carrot starters", "items": {"rabbit": 1, "carrot_patch": 1}},
					{"name": "Berry refuge", "items": {"rabbit": 1, "berry_bush": 1}},
					{"name": "Fresh harvest", "items": {"carrot_patch": 2, "berry_bush": 1}},
					{"name": "Forage patch", "items": {"carrot_patch": 1, "berry_bush": 1}},
				],
				"web": [
					{"name": "Carrot renewal", "items": {"rabbit": 1, "carrot_patch": 1}},
					{"name": "Berry refuge", "items": {"rabbit": 1, "berry_bush": 1}},
					{"name": "Forest balance", "items": {"fox": 1, "carrot_patch": 1}},
					{"name": "Fresh harvest", "items": {"carrot_patch": 2, "berry_bush": 1}},
					{"name": "Wild pair", "items": {"rabbit": 1, "fox": 1}},
					{"name": "Forage patch", "items": {"carrot_patch": 1, "berry_bush": 1}},
				],
				"living": [
					{"name": "Carrot renewal", "items": {"carrot_patch": 2}},
					{"name": "Berry refuge", "items": {"berry_bush": 2}},
					{"name": "Forest balance", "items": {"fox": 1, "carrot_patch": 1}},
					{"name": "Wild balance", "items": {"rabbit": 1, "fox": 1}},
					{"name": "Fresh harvest", "items": {"carrot_patch": 2, "berry_bush": 1}},
					{"name": "Dense forage", "items": {"carrot_patch": 1, "berry_bush": 2}},
				],
			},
			"first_collapse_bundle": {"name": "Carrot starters", "items": {"rabbit": 2, "carrot_patch": 1}},
		},
		"progression": {
			"initial_unlocked": ["rabbit", "carrot_patch", "berry_bush"],
			"initial_supply_pool": "meadow",
			"trend_sample_interval": 1.0,
			"trend_history_duration": 35.0,
			"safe_havens": {
				"minimum_groups": 2,
				"rabbits_per_group": 2,
				"minimum_separation": 300.0,
				"minimum_local_food": 14.0,
			},
			"milestones": [
				{
					"id": "founders_forage",
					"tier": "minor",
					"title": "Founders Find Forage",
					"summary": "Help the founding rabbits find reliable food.",
					"display_populations": ["rabbit"],
					"rabbit_min": 2,
					"fox_min": 0,
					"evidence_type": "founders_fed",
					"distinct_rabbits_fed": 4,
					"rabbit_births": 0,
					"hunts": 0,
					"stabilization": 7.0,
					"decline_window": 10.0,
					"severe_decline_fraction": 0.50,
					"forbid_active_starvation": true,
					"labels": {
						"low": "Gathering the founders...",
						"evidence": "Finding forage...",
						"starving": "Food is out of reach...",
						"declining": "The founders are losing ground...",
						"stabilizing": "Well fed...",
					},
					"teaser": "A well-fed colony may begin a new generation.",
					"completion_message": "The founders have found forage",
					"effects": {},
				},
				{
					"id": "first_new_life",
					"tier": "minor",
					"title": "First New Life",
					"summary": "Support the colony until new life appears.",
					"display_populations": ["rabbit"],
					"rabbit_min": 2,
					"fox_min": 0,
					"evidence_type": "rabbit_birth",
					"rabbit_births": 1,
					"hunts": 0,
					"stabilization": 7.0,
					"decline_window": 12.0,
					"severe_decline_fraction": 0.42,
					"forbid_active_starvation": true,
					"labels": {
						"low": "The colony is still fragile...",
						"evidence": "Waiting for new life...",
						"starving": "The colony needs reachable food...",
						"declining": "The colony is losing ground...",
						"stabilizing": "New life...",
					},
					"teaser": "Can the young generation find its footing?",
					"completion_message": "New life has appeared",
					"effects": {},
				},
				{
					"id": "next_generation",
					"tier": "major",
					"title": "The Next Generation Takes Hold",
					"summary": "Help the young rabbits survive and become part of the colony.",
					"display_populations": ["rabbit"],
					"rabbit_min": 4,
					"fox_min": 0,
					"evidence_type": "born_rabbit_fed",
					"born_survival_age": 8.0,
					"rabbit_births": 0,
					"hunts": 0,
					"stabilization": 9.0,
					"decline_window": 14.0,
					"severe_decline_fraction": 0.40,
					"forbid_active_starvation": true,
					"labels": {
						"low": "The young colony is still fragile...",
						"evidence": "The new generation is finding its feet...",
						"starving": "Young rabbits need reachable food...",
						"declining": "The colony is losing ground...",
						"stabilizing": "Taking hold...",
					},
					"teaser": "Tracks have appeared near the forest edge...",
					"completion_message": "The next generation has taken hold · Foxes have arrived",
					"effects": {
						"expand_world": 145.0,
						"unlock": ["fox"],
						"introduction": {"fox": 2},
						"supply_pool": "web",
						"arm_rabbit_failure": true,
					},
				},
				{
					"id": "first_hunt",
					"tier": "minor",
					"title": "First Hunt",
					"summary": "Introduce a fox when the colony is ready.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 4,
					"fox_min": 1,
					"evidence_type": "living_fox_fed",
					"rabbit_births": 0,
					"hunts": 1,
					"stabilization": 7.0,
					"decline_window": 14.0,
					"severe_decline_fraction": 0.40,
					"forbid_active_starvation": true,
					"labels": {
						"low": "The colony is not ready...",
						"evidence": "Predation begins...",
						"starving": "The prey population needs food...",
						"declining": "Predation is overwhelming the colony...",
						"stabilizing": "The first hunt has passed...",
					},
					"teaser": "Predation has begun. Can the colony renew itself?",
					"completion_message": "The first hunt has passed",
					"effects": {},
				},
				{
					"id": "life_returns",
					"tier": "major",
					"title": "Life Returns",
					"summary": "Help the rabbit colony renew itself after predation begins.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 4,
					"fox_min": 1,
					"evidence_type": "rabbit_birth",
					"rabbit_births": 1,
					"hunts": 0,
					"stabilization": 9.0,
					"decline_window": 16.0,
					"severe_decline_fraction": 0.38,
					"forbid_active_starvation": false,
					"labels": {
						"low": "The food web is still fragile...",
						"evidence": "Waiting for the colony to renew...",
						"starving": "The colony needs food to recover...",
						"declining": "The colony is still losing ground...",
						"stabilizing": "Renewing...",
					},
					"teaser": "The wider meadow could support more than one refuge.",
					"completion_message": "Life returns · the meadow opens",
					"effects": {
						"expand_world": 145.0,
						"introduction": {"fox": 1},
					},
				},
				{
					"id": "two_safe_havens",
					"tier": "minor",
					"title": "Two Safe Havens",
					"summary": "Support viable rabbit groups in more than one part of the meadow.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 4,
					"fox_min": 0,
					"evidence_type": "safe_havens",
					"rabbit_births": 0,
					"hunts": 0,
					"stabilization": 3.0,
					"decline_window": 18.0,
					"severe_decline_fraction": 0.38,
					"forbid_active_starvation": false,
					"labels": {
						"low": "The rabbit groups are still fragile...",
						"evidence": "Spreading out...",
						"starving": "One refuge needs reachable food...",
						"declining": "The colony is losing ground...",
						"stabilizing": "Two havens are holding...",
					},
					"teaser": "A wider prey base may support another predator.",
					"completion_message": "Two safe havens are holding",
					"effects": {},
				},
				{
					"id": "predators_find_place",
					"tier": "major",
					"title": "Predators Find Their Place",
					"summary": "Support more than one fox without breaking the rabbit population.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 6,
					"fox_min": 2,
					"evidence_type": "two_foxes_fed_and_birth",
					"distinct_foxes_fed": 2,
					"rabbit_births": 1,
					"hunts": 0,
					"stabilization": 11.0,
					"decline_window": 20.0,
					"severe_decline_fraction": 0.36,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The food web cannot support both predators yet...",
						"evidence": "The predators are finding their place...",
						"starving": "The food web is under pressure...",
						"declining": "Predation is overwhelming the colony...",
						"stabilizing": "Finding balance...",
					},
					"teaser": "Can the whole web sustain itself?",
					"completion_message": "Predators have found their place · the meadow opens",
					"effects": {
						"expand_world": 145.0,
						"introduction": {"fox": 1},
						"supply_pool": "living",
					},
				},
				{
					"id": "living_ecosystem",
					"tier": "final",
					"title": "Living Ecosystem",
					"summary": "Sustain renewal and predation while both populations remain healthy.",
					"display_populations": ["rabbit", "fox"],
					"rabbit_min": 6,
					"fox_min": 2,
					"evidence_type": "ordered_cycle",
					"rabbit_births": 0,
					"hunts": 0,
					"event_sequence": ["birth", "hunt", "birth", "hunt"],
					"evidence_window": 180.0,
					"stabilization": 18.0,
					"decline_window": 24.0,
					"severe_decline_fraction": 0.34,
					"forbid_active_starvation": true,
					"forbid_fox_starvation": true,
					"labels": {
						"low": "The food web is under strain...",
						"evidence": "Life is finding its rhythm...",
						"starving": "The food web needs support...",
						"declining": "The web is beginning to unravel...",
						"stabilizing": "Holding together...",
					},
					"teaser": "Can the web hold together?",
					"completion_message": "Ecosystem Established",
					"effects": {"complete_run": true},
				},
			],
			"critical": {
				"breeding_group": 2,
				"entry_debounce": 4.0,
				"recovery_population": 2,
				"recovery_settling": 8.0,
				"grace_duration": 45.0,
				"first_rescue_delay": 6.0,
				"recent_event_window": 90.0,
			},
		},
	}
